export const genres = [
  'Early Access',
  'Video Production',
  'Web Publishing',
  'Accounting',
  'Episodic',
  'Animation & Modeling',
  'Strategy',
  'Free to Play',
  '360 Video',
  'Simulation',
  'Action',
  'Gore',
  'Game Development',
  'Audio Production',
  'Software Training',
  'Racing',
  'Utilities',
  'Design & Illustration',
  'Violent',
  'Casual',
  'RPG',
  'Movie',
  'Photo Editing',
  'Adventure',
  'Sports',
  'Massively Multiplayer',
  'Indie',
  'Tutorial',
  'Short',
  'Education',
  'Documentary'
]

export const languages = [
  'Uzbek',
  'Maori',
  'Simplified Chinese',
  'Latvian',
  'Korean[b',
  'Italian[b',
  'Tajik',
  'Sinhala',
  'Indonesian',
  'Welsh',
  'Portuguese',
  'Greek',
  'Hindi',
  'Luxembourgish',
  'Bangla',
  'Kinyarwanda',
  'Albanian',
  'Slovak',
  'Portuguese - Brazil',
  'Ukrainian',
  'Sorani',
  'Tamil',
  'Dutch',
  'Icelandic',
  'Sotho',
  'Xhosa',
  'Gujarati',
  'Galician',
  'America',
  'Khmer',
  'Urdu',
  'Lithuanian',
  'Quechua',
  'Norwegian',
  'Kannada',
  'Russian',
  'Basque',
  'Marathi',
  'Punjabi ',
  'Irish',
  'Vietnamese',
  'Armenian',
  'Swahili',
  'Spanish - Spain',
  'Japanese',
  'Polish',
  'Afrikaans',
  'Turkish',
  'Amharic',
  'Tatar',
  'Filipino',
  'Valencian',
  'Sindhi',
  'Danish',
  'Finnish',
  'Maltese',
  'English Dutch',
  'Kazakh',
  'Nepali',
  'Gurmukhi',
  'Romanian',
  'Malay',
  'Yoruba',
  'Italian ',
  'Serbian',
  'Persian',
  'Bulgarian',
  'German[b',
  'Dari',
  'Hungarian',
  'Catalan',
  'Traditional Chinese',
  'German',
  'Hebrew',
  'Belarusian',
  'Assamese',
  'Wolof',
  'Macedonian',
  'Turkmen',
  'Tigrinya',
  'Japanese ',
  'Zulu',
  'English',
  'Mongolian',
  'Bosnian',
  'Slovakian',
  'Konkani',
  'Malayalam',
  'Georgian',
  'Portuguese - Portugal',
  'Arabic',
  'Slovenian',
  'Shahmukhi',
  'Croatian',
  'Odia',
  'Italian',
  'Azerbaijani',
  'Estonian',
  'Igbo',
  'Uyghur',
  'Telugu',
  'Spanish - Latin',
  'English ',
  'English[b',
  'Scots',
  'Thai',
  'Tswana',
  'Cherokee',
  'French[b',
  'Korean',
  'Swedish',
  'Hausa',
  'Kyrgyz',
  'French',
  'Czech'
]
